# Site settings
title: Ion
email: tkaralidi@ucf.edu
description: Welcome! I am Theodora Karalidi a theoretical astrophysist working on exoplanet
  and brown dwarf atmospheres.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.io/tkaralidi" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  tkaralidi

# Build settings
markdown: kramdown
