#theme: jekyll-theme-tactile

# Site wide configuration

title: Theodora Karalidi
locale: en_US
logo: # filename of a logo image to come

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Theodora Karalidi
  avatar: bio-photo.jpg
