theme: jekyll-theme-tactile

# Site wide configuration

title: Theodora Karalidi
markdown: kramdown
logo: ![Add an Image](images/bio-photo.jpg)

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Theodora Karalidi
  avatar: bio-photo.jpg
